### ISSUE TITLE
return code 0 on failed deployment

### ISSUE THREAD

**Issue by Shaboxi** [reactiveops/reckoner#105] opened 2019-05-28 15:16 UTC
hi guys, 
when im installing my charts (happens even if i use the '--only' flag) ive noticed that if the helm command isnt able to install the chart reckoner still give back a return code 0. 

is it on purpose? theres a way to make the installation strict?

**Comment by ejether** [comment] 2019-05-28 17:21
Hi @Shaboxi , thanks for reporting this issue.  This is the expected behavior based on the code path, but it is not ideal. We have some current work addressing this exact issue so I'll close this as a duplicate of https://github.com/reactiveops/reckoner/issues/86

**Closed by ejether** 2019-05-28 17:21 UTC
Labels: duplicate
